### ISSUE TITLE
fatal error LNK1181: cannot open input file 'x64-msvcrt-ruby270.lib'

### ISSUE THREAD

**Issue by prodprogramming** [danielpclark/rutie#117]
Hello everyone,

I'm having some issues here. I am attempting to compile my sample code, using the "Using Ruby in Rust" sample on the crates.io [repository](https://crates.io/crates/rutie). 

I am using Windows 10 64bit, and compiling using rutie v0.7.0 as well as Ruby 2.7.1.

Upon compilation, I receive a linker error _fatal error LNK1181: cannot open input file 'x64-msvcrt-ruby270.lib'_. I have searched through my Ruby27-x64 directory, and am unable to find the .lib file mentioned. I have found a .dll equivalent however, but this doesn't help me.

Any help is appreciated. Thank you guys

**Comment by danielpclark** [comment]
Ruby 2.7 is not yet supported.  Windows has limited support with some issues noted in others PRs.  I plan to get RuTie updated for Ruby 2.7 this July.

**Comment by danielpclark** [comment]
Ruby 2.7 is supported on most O.S.s and Ruby 3.0 has limited support.  We have additional linking support incorporated into the build process and an option to not link with the `no-link` flag used in `Cargo.toml` if that better fits your needs.

Feel free to reopen this issue if it still persists.
