### ISSUE TITLE
Docs for version 0.8.0 build failed

### ISSUE THREAD

**Issue by abinoam** [danielpclark/rutie#126]
https://docs.rs/crate/rutie/0.8.0/builds/272356

**Comment by danielpclark** [comment]
Interesting... I didn't know about this.  I think the first step would be to build the docs locally and see if that works before proceeding in diagnosing this.

**Comment by pwoolcoc** [comment]
It looks like it's failing when trying to create `target/<profile>/deps`. Typically build scripts are supposed to put artifacts in `ENV['OUT_DIR']`, so rutie should probably put the symlink to the .so there instead?

**Comment by danielpclark** [comment]
This is resolved for v0.8.2
