### ISSUE TITLE
Version 0.8.4 tagged but not pushed to crates.io

### ISSUE THREAD

**Issue by ankane** [danielpclark/rutie#155]
Hi, not sure if this is intentional, but it looks like 0.8.4 was tagged yesterday (df5930d912ee1afc7a2af8999386871a66fbc9ab), but hasn't been pushed to [crates.io](https://crates.io/crates/rutie/versions).

**Comment by danlarkin** [comment]
Just echoing this, it would be nice to have 49329f7715ae791f369a67ecaafe9fb428073c24 released.

**Comment by danielpclark** [comment]
@ankane & @danlarkin Thanks for catching this.  It's up!

**Comment by ankane** [comment]
Thanks @danlarkin!
