### ISSUE TITLE
Running tests with static Ruby library fails

### ISSUE THREAD

**Issue by felix-d** [danielpclark/rutie#57]
I installed ruby 2.5.3 with `ruby-install` and the static library file name I get is `libruby.2.5.3-static.a`. When `rustc` passes down arguments to the `gcc` linker, the `l` option is used. This option adds the `lib` prefix automatically. Therefore, I had to change a few things for `cargo test` to run properly.

See changes [here](https://github.com/danielpclark/rutie/pull/58).

Also, there is an [issue](https://github.com/danielpclark/rutie/issues/45) about some tests not running properly and in the documentation, it says support for static linking is incomplete, but all tests ran on my end. Was this fixed?

**Comment by danielpclark** [comment]
> Also, there is an issue about some tests not running properly and in the documentation, it says support for static linking is incomplete, but all tests ran on my end. Was this fixed?

As you can see here: https://travis-ci.org/danielpclark/rutie/jobs/465793207 the issues remain.
