### ISSUE TITLE
AnyException can only be constructed for top-level error types

### ISSUE THREAD

**Issue by daniel-ferguson** [danielpclark/rutie#80]
As far as I can tell it's not possible to construct an `AnyException` for an error type that isn't in the top-level namespace.

Given a library that defines a custom error type:
```ruby
class MyGem
  class MyError < StandardError; end
end
```

I can't construct an `AnyException` by passing this error type's name to `AnyException::new`, the following panics: `AnyException::new("MyGem::MyError", None)`.

I suspect the underlying issue is that [`AnyException::new`](https://github.com/danielpclark/rutie/blob/7d494e2a4399092a414398bfe8e333cb3d3af128/src/class/traits/exception.rs#L27-L32) uses [`Class::from_existing`](https://github.com/danielpclark/rutie/blob/7d494e2a4399092a414398bfe8e333cb3d3af128/src/class/class.rs#L135-L139), which seems to only look up items in the top-level namespace as it always passes `rb_cObject` as the first argument to `const_get`.

As far as I can tell it looks like the way to get access to nested classes/modules using `rutie` is:
```rust
use rutie::Class;

let my_gem = Class::from_existing("MyGem");
let my_error = my_gem::get_nested_class("MyError");
```
But I can't find a way to initialize an exception with that `my_error`object.

*Thank you for your work on this library, it's been a pleasure to use.*

**Comment by danielpclark** [comment]
Thank you.  I see your point.  Let me consider the best way to deal with this.

**Comment by danielpclark** [comment]
That should do it @daniel-ferguson .  It's in the v0.5.4 release.
